// Code generated by hertz generator.

package school_struct

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/school_struct"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCollegeList .
// @router /school/college/list [GET]
func GetCollegeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetCollegeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	colleges, total, err := service.NewSchoolStructService(ctx, c).GetCollegeList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetCollegeListResp)
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Total = total
	resp.CollegeList = colleges

	pack.SendResponse(c, resp)
}

// GetMajorList .
// @router /school/major/list [GET]
func GetMajorList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetMajorListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 调用服务层
	majors, total, err := service.NewSchoolStructService(ctx, c).GetMajorList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetMajorListResp)

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Total = total
	resp.MajorList = majors

	pack.SendResponse(c, resp)
}

// GetTeacherList .
// @router /school/teacher/list [GET]
func GetTeacherList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetTeacherListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 调用服务层
	teachers, total, err := service.NewSchoolStructService(ctx, c).GetTeacherList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetTeacherListResp)

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Total = total
	resp.TeacherList = teachers

	pack.SendResponse(c, resp)
}

// GetTeacherDetail .
// @router /api/school/teacher/detail [GET]
func GetTeacherDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetTeacherDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetTeacherDetailResp)
	data, err := service.NewSchoolStructService(ctx, c).GetTeacherDetail(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Data = data

	pack.SendResponse(c, resp)
}
